# ■Week2授業前課題3 行列積のスクラッチ

## 1.このテキストについて

テキストの目的
数式演算ライブラリのNumPyに慣れる
行列演算に慣れる

どのように学ぶか
行列積の計算を手計算で行った後、スクラッチ実装することで理解を深めていきます。

## 2.行列積

以下のような行列A、Bを考えます。


A
=
⎡
⎢
⎣
−
1
2
3
4
−
5
6


7
8
−
9
⎤
⎥
⎦
,
B
=
⎡
⎢
⎣
0
2
1
0
2
−
8
2
9
−
1
⎤
⎥
⎦

NumPyで表すと次のようになります。

import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])


## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。

[計算過程]
$$
    \boldsymbol{AB} =
        \left[\begin{array}{ccc}
            ab_{0,0} = a_{0,0}* b_{0,0} + a_{0,1}*b_{1,0} +a_{0,2}*b_{2,0} & \cdots & ab_{0,x}\\
            \vdots  & \ddots & \vdots \\
            ab_{y,0} & \cdots & a_{y,x} \\
        \end{array}\right]
$$

にならい

$$
    \boldsymbol{AB} =
        \left[\begin{array}{ccc}
            ab_{0,0} = (-1)*0 + 2*0+3*2 & ab_{0,1} = (-1)*2 + 2*2 + 3*9 & ab_{0,2} = (-1)*1 + 2*(-8) + 3*(-1)\\
            ab_{1,0} = 4*0+(-5)*0+6*2 & ab_{1,1} = 4*2 + (-5)*2 + 6*9 & ab_{1,2} = 4*1 + (-5)*(-8) + 6*(-1)\\
            ab_{2,0} = 7*0 + 8*0+(-9)*2 & ab_{2,1} = 7*2 + 8*2 + (-9)*9 & ab_{2,2} = 7*1 + 8*(-8) + (-9)*(-1)\\
        \end{array}\right]
$$

全て計算し以下解答となった。

# A：([[6 , 29, -20], [12, 52, 38], [-18, -51, -48]])
行列積ABはAの行数とBの列数の行列になる。今回はAもBも３行３列の行列のため、Aの行＝３とBの列＝３で３×３の行列となる。
Aの１列目＊Bの１行目の和・・・Aのｍ列＊Bのn行まで繰り返し、AB行列のｍ行n列の値になる。
行列積はABとBAで基準の行列がどちらになるかで全く違うという特徴もある。

## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。


numpy.matmul — NumPy v1.16 Manual


numpy.dot — NumPy v1.16 Manual


《3種類の違い》


np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。


今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。


If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

matmul_ab = np.matmul(a_ndarray, b_ndarray)
print(matmul_ab)

dot_ab = np.dot(a_ndarray, b_ndarray)
print(dot_ab)

mark_ab = a_ndarray @ b_ndarray
print(mark_ab)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 3.行列積のスクラッチ実装

np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

## 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる
行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる
行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる
それらの値を全て足し合わせる

数式で表すと

2
∑
k
=
0
 
a
0
,
k
b
k
,
0

です。


この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [2]:
"""
for分作成のため整理

n1 = a_ndarray[0, 0] * b_ndarray[0, 0]
n2 = a_ndarray[0, 1] * b_ndarray[1, 0]
n3 = a_ndarray[0, 2] * b_ndarray[2, 0]
n4 = a_ndarray[0, 0] * b_ndarray[0, 1]
n5 = a_ndarray[0, 1] * b_ndarray[1, 1]
n6 = a_ndarray[0, 2] * b_ndarray[2, 1]
n7 = a_ndarray[0, 0] * b_ndarray[0, 2]
n8 = a_ndarray[0, 1] * b_ndarray[1, 2]
n9 = a_ndarray[0, 2] * b_ndarray[2, 2]
n10 = a_ndarray[1, 0] * b_ndarray[0, 0]
n11 = a_ndarray[1, 1] * b_ndarray[1, 0]
n12 = a_ndarray[1, 2] * b_ndarray[2, 0]
n13 = a_ndarray[1, 0] * b_ndarray[0, 1]
n14 = a_ndarray[1, 1] * b_ndarray[1, 1]
n15 = a_ndarray[1, 2] * b_ndarray[2, 1]
n16 = a_ndarray[1, 0] * b_ndarray[0, 2]
n17 = a_ndarray[1, 1] * b_ndarray[1, 2]
n18 = a_ndarray[1, 2] * b_ndarray[2, 2]
n19 = a_ndarray[2, 0] * b_ndarray[0, 0]
n20 = a_ndarray[2, 1] * b_ndarray[1, 0]
n21 = a_ndarray[2, 2] * b_ndarray[2, 0]
n22 = a_ndarray[2, 0] * b_ndarray[0, 1]
n23 = a_ndarray[2, 1] * b_ndarray[1, 1]
n24 = a_ndarray[2, 2] * b_ndarray[2, 1]
n25 = a_ndarray[2, 0] * b_ndarray[0, 2]
n26 = a_ndarray[2, 1] * b_ndarray[1, 2]
n27 = a_ndarray[2, 2] * b_ndarray[2, 2]

"""

# print(n1)
# print(n2)
# print(n3)

matmul_list = np.array([])
# print(matmul_list)

for n in range(3):
    for j in range(3):
        matmul_sum = 0
        for i in range(3):
            matmul_1 = a_ndarray[n, i] * b_ndarray[i, j]
            matmul_sum += matmul_1
            # print(matmul_sum)
        matmul_list = np.append(matmul_list, matmul_sum)

matmul_list_reshape = matmul_list.reshape(3, 3)
print(matmul_list_reshape)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。


c
i
,
j
=
2
∑
k
=
0
 
a
i
,
k
b
k
,
j

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。

In [3]:
#行列積の関数
def matrix_dot(matrix1, matrix2):
    array1 = np.array(matrix1)
    array2 = np.array(matrix2)
    
    matmul_list = np.array([])
    
    for n in range(matrix1.shape[0]):
        for j in range(matrix2.shape[1]):
            matmul_sum = 0
            for i in range(matrix1.shape[0]):
                matmul_1 = a_ndarray[n, i] * b_ndarray[i, j]
                matmul_sum += matmul_1
                # print(matmul_sum)
            matmul_list = np.append(matmul_list, matmul_sum)
    
    matmul_list_reshape = np.reshape(matmul_list,(matrix1.shape[0], matrix2.shape[1]))

    return matmul_list_reshape

a_ndarray = np.array([[1,2],[4,5]])
b_ndarray = np.array([[3,4],[5,6]])

ab_dot_ndarray = matrix_dot(a_ndarray, b_ndarray)
print(ab_dot_ndarray)


# 3*3行列同士の積でも答え合わせ済
# 上記2*2の行列積は別セルにて答え合わせ済

[[13. 16.]
 [37. 46.]]


## 行列積が定義されない組み合わせの行列

次に以下のような例を考えます。


D
=
[
−
1
2
3
4
−
5
6
]
,
E
−
=
[
−
9
8
7
6
−
5
4
]

1
2
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [6]:
# if文追加　行列Aの行数と行列Bの列数が同数の場合のみ計算とする

def matrix_dot_if(matrix1, matrix2):
    array1 = np.array(matrix1)
    array2 = np.array(matrix2)
    
    matmul_list = np.array([])
    
    if matrix1.shape[0] == matrix2.shape[1]:
        for n in range(matrix1.shape[0]):
            for j in range(matrix2.shape[1]):
                matmul_sum = 0
                for i in range(matrix1.shape[0]):
                    matmul_1 = a_ndarray[n, i] * b_ndarray[i, j]
                    matmul_sum += matmul_1
                    # print(matmul_sum)
                matmul_list = np.append(matmul_list, matmul_sum)

        matmul_list_reshape = np.reshape(matmul_list,(matrix1.shape[0], matrix2.shape[1]))

        return matmul_list_reshape
    
    else:
        print("行列積はできません")        

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

de = matrix_dot_if(d_ndarray, e_ndarray)
de


行列積はできません


## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。


numpy.transpose — NumPy v1.16 Manual


numpy.ndarray.T — NumPy v1.16 Manual

In [8]:
# 転置（.T）してから行列積
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

de = np.dot(d_ndarray, e_ndarray.T)
de

array([[ 46,  -4],
       [-34,  73]])

## 参考
numpyの行列数取得について：https://note.nkmk.me/python-numpy-ndarray-ndim-shape-size/

## 備忘録
所要時間：５ｈ　for文問題でつまづいた。